version: "3.7"
# docker network create --driver overlay overlay-network --attachable
networks:
  overlay-network:
    external: true
# docker volume create --name certbot
volumes:
  certbot:
    external: true
services:
  nginx:
    image: bzdvdn/nginx-gateway-ingress
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certbot:/etc/letsencrypt/
    networks:
      - overlay-network
    environment:
      WITH_SSL: "1"
      CERTBOT_EMAIL: "support@smartanalytics.io"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
